/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as RideRouteImport } from './routes/ride'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DestinationIdRouteImport } from './routes/destination.$id'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const RideRoute = RideRouteImport.update({
  id: '/ride',
  path: '/ride',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationIdRoute = DestinationIdRouteImport.update({
  id: '/destination/$id',
  path: '/destination/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ride': typeof RideRoute
  '/saved': typeof SavedRoute
  '/destination/$id': typeof DestinationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ride': typeof RideRoute
  '/saved': typeof SavedRoute
  '/destination/$id': typeof DestinationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ride': typeof RideRoute
  '/saved': typeof SavedRoute
  '/destination/$id': typeof DestinationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ride' | '/saved' | '/destination/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ride' | '/saved' | '/destination/$id'
  id: '__root__' | '/' | '/ride' | '/saved' | '/destination/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RideRoute: typeof RideRoute
  SavedRoute: typeof SavedRoute
  DestinationIdRoute: typeof DestinationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ride': {
      id: '/ride'
      path: '/ride'
      fullPath: '/ride'
      preLoaderRoute: typeof RideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination/$id': {
      id: '/destination/$id'
      path: '/destination/$id'
      fullPath: '/destination/$id'
      preLoaderRoute: typeof DestinationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RideRoute: RideRoute,
  SavedRoute: SavedRoute,
  DestinationIdRoute: DestinationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
